lfcp:
  application:
    type: ssr
    base-package: lfcp.ssr.
    web:
      csrf:
        use-csrf-filter: true # CSRF 적용여부
        timeout: -1 # 단위:초, -1(제한없음)
        unchecked-paths:
          /login/**
          , /member/v1/apps/push/**
          , /member/v1/mail/receive/**

server:
  port: 8761
#  servlet:
#    session:
#      cookie:
#        name: JSESSIONID
#        http-only: true
#        secure: false
#        path: /
#        domain: localhost
#        base64-encoding: false
#      #        same-site: none
#      timeout: 30m
#  error:
#    include-exception: false
#    include-stacktrace: never


spring:
  application:
    name: service-discovery
#  security:
#    user:
#      name: admin
#      password: admin
  boot:
    admin:
      url: http://localhost:8761
      client:
        url: http://localhost:8761
#        username: admin
#        password: admin
        instance:
          metadata:
            user.name: admin
            user.password: admin
          service-url: http://localhost:8011
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    register-with-eureka: false # 유레카 서비스에 (자신을) 등록 여부
    fetch-registry: false  # (유레카 클라이언트 기반) 다른 서비스들의 정보를 fetch 유무
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # 설정을 하지 않으면 기본 http://localhost:8761/ 로 연동된다.

  server:
    wait-time-in-ms-when-sync-empty: 5  # 서버가 요청을 받기 전 대기할 초기 시간(ms) : 거의 대기 없음 (default 5분 : 상용에서는 모든 서비스가 등록 되길 기다리기 위해 5분 후 정보를 공유)

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
